# Generated by Django 3.2 on 2021-07-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khabar', '0003_auto_20210702_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchlog',
            name='search_at',
            field=models.DateTimeField(),
        ),
    ]
